
export const vehicles = [
  {
    id: 1,
    make: 'Gallivanter',
    model: 'Baller ST',
    price: 89000,
    description: 'A powerful and luxurious SUV with a commanding presence. Perfect for both city driving and off-road adventures. This Baller ST is packed with features and offers a smooth, comfortable ride.',
    type: 'SUV',
    image: 'suv-1-a',
  },
  {
    id: 2,
    make: 'Benefactor',
    model: 'Schafter V12',
    price: 116000,
    description: 'The epitome of luxury and performance. The Schafter V12 combines a sleek design with a monstrous engine, offering an exhilarating driving experience. Meticulously maintained and in pristine condition.',
    type: 'Sedan',
    image: 'sedan-1-a',
  },
  {
    id: 3,
    make: 'Bravado',
    model: 'Bison',
    price: 45000,
    description: 'A rugged and reliable pickup truck that\'s ready for any job. The Bravado Bison is a workhorse with a spacious cabin and plenty of power for hauling and towing.',
    type: 'Off-road',
    image: 'truck-1-a',
  },
  {
    id: 4,
    make: 'Obey',
    model: 'Rocoto',
    price: 65000,
    description: 'A stylish and versatile SUV that offers a perfect blend of comfort and performance. With its sporty design and advanced features, the Rocoto is an excellent choice for any driver.',
    type: 'SUV',
    image: 'suv-2-a',
  },
  {
    id: 5,
    make: 'Dewbauchee',
    model: 'Exemplar',
    price: 95000,
    description: 'A grand tourer that perfectly blends performance and luxury. With its elegant lines and powerful engine, the Exemplar provides a driving experience that is both thrilling and comfortable.',
    type: 'Coupe',
    image: 'sedan-2-a',
  },
  {
    id: 6,
    make: 'Vapid',
    model: 'Guardian',
    price: 78000,
    description: 'A heavy-duty truck built to handle the toughest conditions. The Vapid Guardian is a behemoth on the road, offering unmatched towing capacity and a commanding view of the road.',
    type: 'Off-road',
    image: 'truck-2-a',
  },
  {
    id: 7,
    make: 'Enus',
    model: 'Cognoscenti',
    price: 154000,
    description: 'Experience unparalleled luxury with the Enus Cognoscenti. This flagship sedan offers a first-class cabin, cutting-edge technology, and a serene ride quality for the discerning driver.',
    type: 'Sedan',
    image: 'sedan-3-a',
  }
];
